name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb:11.2
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: app_test
          MARIADB_USER: app
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Lint Yaml
      run: php bin/console lint:yaml config

    - name: Lint Twig
      run: php bin/console lint:twig templates

    - name: PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: PHPStan
      run: |
        php bin/console cache:warmup --env=dev
        vendor/bin/phpstan analyze --no-progress --memory-limit=512M

    - name: Wait for MariaDB
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Database setup
      env:
        DATABASE_URL: mysql://app:password@127.0.0.1:3306/app_test?serverVersion=mariadb-11.2.2&charset=utf8mb4
      run: |
        php bin/console doctrine:database:create --env=test --if-not-exists
        php bin/console doctrine:migrations:migrate --env=test --no-interaction
        php bin/console doctrine:schema:validate --env=test --skip-sync

    - name: Run Tests
      env:
        DATABASE_URL: mysql://app:password@127.0.0.1:3306/app_test?serverVersion=mariadb-11.2.2&charset=utf8mb4
      run: php bin/phpunit
